# Generated by Django 5.0 on 2023-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cabañas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_cabaña',
            name='image',
        ),
        migrations.AddField(
            model_name='tipo_cabaña',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
