# Generated by Django 5.0 on 2023-12-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comodidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidad',
            name='image',
        ),
        migrations.AddField(
            model_name='comodidad',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
