# Generated by Django 5.0 on 2023-12-05 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comodidades', '0001_initial'),
        ('tipo_cabañas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('availability', models.CharField(max_length=10)),
                ('value', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='book_images')),
                ('comodidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comodidades.comodidad')),
                ('tipo_cabaña', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_cabañas.tipo_cabaña')),
            ],
        ),
    ]
