# Generated by Django 5.0 on 2023-12-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabaña',
            name='image',
        ),
        migrations.AddField(
            model_name='cabaña',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
