# Generated by Django 5.0 on 2023-12-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabañas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('number_people', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='book_images')),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabañas.cabaña')),
            ],
        ),
    ]
